In [205]:
#Import libraries
import pandas as pd
import numpy as np
import gensim.downloader as api
from gensim.models.word2vec import Word2Vec
from transformers import pipeline
import warnings
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import silhouette_score

In [206]:
#Read in 'twitter_df'
twitter_df = pd.read_csv("../dataset/twitter_df.csv")

In [207]:
twitter_df.shape

(22153, 8)

In [208]:
twitter_df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [209]:
#Create our contextual stop words
stops = ["online", "home", "remote", "work", "working","pandemic","business", \
               "internet", "remotework", "online","team","office","company","hybrid","employee","looking"]

In [210]:
len(twitter_df[twitter_df.duplicated("tweets")])

4557

In [211]:
# originaltweets =twitter_df.drop_duplicates(subset=['tweets'], keep='first').reset_index(drop=True)

In [212]:
originaltweets = twitter_df[~twitter_df['tweets'].str.contains('RT')]

In [213]:
originaltweets = originaltweets.reset_index(drop=True)

In [214]:
originaltweets =originaltweets.drop_duplicates(subset=['cleaned_tweets'], keep='first').reset_index(drop=True)

In [215]:
originaltweets.shape

(10781, 7)

In [216]:
X = originaltweets['cleaned_tweets']
X.head()

0    rise slowly becoming normal which mean need re...
1    opportunity join fantastic team tech fast pace...
2    good news open this excellent report from remo...
3            four way energize post pandemic workforce
4    these tool that will save your google meet too...
Name: cleaned_tweets, dtype: object

### CV

In [238]:
#https://stackoverflow.com/questions/39303912/tfidfvectorizer-in-scikit-learn-valueerror-np-nan-is-an-invalid-document
#https://stackoverflow.com/questions/27697766/understanding-min-df-and-max-df-in-scikit-countvectorizer
cv = CountVectorizer(max_features=5000, min_df=30, max_df=0.5, stop_words=stopwords.words('english')) 
X_cv = cv.fit_transform(X.values.astype('U'))

In [239]:
len(cv.get_feature_names())

579

In [240]:
X_cv_df = pd.DataFrame(X_cv.toarray(), columns = cv.get_feature_names())

In [241]:
df = pd.concat([originaltweets, X_cv_df], axis=1)

In [242]:
df = df.reset_index(drop=True)

In [243]:
df.head()

,tweet_id,tweet_posted_on,tweets,cleaned_tweets,user_location,user_location_cleaned,polarity,ability,able,access,...,workspace,world,worth,would,writer,writing,year,youtube,zero,zoom
0,1416181616846811137,2021-07-16 23:43:03+00:00,üè° #RemoteWork is on the rise &amp; slowly beco...,rise slowly becoming normal which mean need re...,"New York, NY",US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1416181380279635970,2021-07-16 23:42:07+00:00,Opportunity to join a fantastic team at a hi-t...,opportunity join fantastic team tech fast pace...,London | New York,US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1416181225979473920,2021-07-16 23:41:30+00:00,Good news for #JobSeekers open to #RemoteWork!...,good news open this excellent report from remo...,Sydney | Hong Kong | Singapore,HK,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1416180635903868934,2021-07-16 23:39:09+00:00,Four Ways to Energize a Post-Pandemic Workforc...,four way energize post pandemic workforce,"Chicago, IL",US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1416180231350759425,2021-07-16 23:37:33+00:00,üöë These are the tools that will save your #Rem...,these tool that will save your google meet too...,"Duluth, GA",US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [244]:
cv_col = df.columns[7:]
cv_col_names = df[cv_col]

In [245]:
X_cv=cv_col_names
sc = StandardScaler()
X_cv_sc = sc.fit_transform(X_cv)
X_cv_sc[0:1]

array([[-0.05370029, -0.06334373, -0.07801458, -0.05456208, -0.09486351,
        -0.06260278, -0.07418022, -0.05624654, -0.0528246 , -0.06253782,
        -0.08856383, -0.06376264, -0.06401546, -0.05624654, -0.05947425,
         9.76006806, -0.08594379, -0.06961808, -0.05541064, -0.07046215,
        -0.07465665, -0.05715419, -0.06894221, -0.12931979, -0.05357606,
        -0.0704612 , -0.25886036, -0.06203245, -0.06260278, -0.07369983,
        -0.10441915, -0.09587184, -0.0716525 , -0.09177314, -0.05896602,
        -0.07230279, -0.15622853, -0.07294743, -0.07390186, -0.10435004,
        -0.05292836, -0.09931893, 18.04717853, -0.06253782,  8.28043591,
         5.55037751, -0.11362618, -0.05903339, -0.0966816 , -0.05796321,
        -0.08051791, -0.05947425, -0.06373209, -0.08184415, -0.06999544,
        -0.06328088, -0.0992398 , -0.08373423, -0.22924572, -0.11109778,
        -0.05737391, -0.06934696, -0.08373423, -0.06185315, -0.05715419,
        -0.06127147,  8.28124764, -0.05796321, -0.11060345, -0.0716525 ,
        -0.0640763 , -0.05876133, -0.22985219, -0.05456208, -0.06791604,
        -0.10744122, -0.09054995, -0.0885998 , -0.05005784, -0.0528246 ,
        -0.06567168, -0.05292836,  8.25306829, -0.05868375, -0.07480971,
        -0.05896602, -0.0930747 , -0.08380662, -0.20772684, -0.11922534,
        -0.12312626, -0.07023424, -0.05868375, -0.06102498, -0.07801458,
        -0.07727755, -0.05541064, -0.09478691, -0.07474002, -0.09177314,
        -0.06334373, -0.05633382, -0.05490306, -0.06334373, -0.11967225,
        -0.05947425, -0.0669144 , -0.10655459, -0.09108293, -0.06102498,
        -0.0520488 , -0.08584432, -0.1424904 , -0.05656177, -0.11470248,
        -0.11779594, -0.11575183, -0.07354546, -0.05737391, -0.05624654,
        -0.08797413, -0.09751222, -0.09206579, -0.07848305, -0.16810141,
        -0.09907995, -0.06844871, -0.12206053, -0.08267954, -0.06025453,
        -0.06328088, -0.05728807, -0.10036731, -0.09619519, -0.06079938,
        -0.06923266, -0.10255956, -0.05292836, -0.05370029, -0.08613383,
        -0.06894221, -0.06102498, -0.06025453, -0.0863912 ,  3.75507064,
        -0.1079846 , -0.05707036, -0.2376969 , -0.09005763, -0.06260278,
        -0.06203245, -0.06551743, -0.06200169, -0.10247424, -0.05292836,
        -0.06687442, -0.059549  , -0.06474184, -0.05465701, -0.10966572,
        -0.06203245, -0.08700628, -0.09724674, -0.08601808, -0.06401546,
        -0.08199583, -0.0864635 , -0.05624654, -0.12566518, -0.08808212,
        -0.07437332, -0.06200169, -0.05868375, -0.0783574 , -0.07242153,
        -0.05525731, -0.06528897, -0.08861529, -0.1011266 , -0.0615528 ,
        -0.05868375, -0.05465701, -0.07557813, -0.15325342, -0.05541064,
        -0.06277654, -0.11257171, -0.08369837, -0.0767044 , -0.11927344,
        -0.07242153, -0.09380611, -0.05456208, -0.05868375, -0.05541064,
        -0.06401546, -0.06961808, -0.05541064, -0.0528246 , -0.17143307,
        -0.05525731, -0.05649999, -0.07225957, -0.1082955 , -0.06844871,
        -0.05947425, -0.18613516, -0.0640763 , -0.11933837, -0.06103676,
        -0.08757082, -0.09628913, -0.05370029, -0.08721551, -0.05947425,
        -0.1244224 , -0.12528688, -0.07090301, -0.05541064, -0.14047283,
        -0.0814514 , -0.05465701, 11.35306792, -0.07028757, -0.08436472,
        -0.0548705 , -0.09436526, -0.07422034, -0.07605341, -0.09457577,
        -0.05624654, -0.05656177, -0.19914665, -0.059549  , -0.08316363,
        -0.0578826 , -0.08721551, -0.23213572, -0.35945922, -0.05204303,
        -0.1148233 , -0.05465701, -0.05947425, -0.15541181, -0.0774124 ,
        -0.07099639, -0.09579748, -0.07791751, -0.0578826 , -0.08025817,
        -0.08769936, -0.08224115, -0.05776298, -0.05184445, -0.07680568,
        -0.08914536, -0.06448334, -0.05707036, -0.06474184, -0.0528246 ,
        -0.06894221, -0.05624654, -0.08069772, -0.05796321, -0.07533582,
        -0.06277654, -0.06692823, -0.05853889, -0.06319391, -0.15057969,
        -0.19092262, -0.07826522, -0.12474788, -0.05204303, -0.15261146,
        -0.06155478, -0.08863945, -0.08916912, -0.07756472, -0.11955431,
        -0.09635853, -0.05379947, -0.17750195, -0.07279126, -0.05868375,
        -0.05876133, -0.05370029, -0.07099639, -0.1656056 , -0.16388494,
        -0.05204303, -0.06912614, -0.11798916, -0.08224115, -0.08087285,
        -0.10389539, -0.06334373, -0.10130208, -0.0555016 , -0.09577815,
        -0.05319505, -0.12909287, -0.19008649, -0.10110514, -0.05184445,
        -0.09228543, -0.0578826 , -0.0528246 , -0.21957261, -0.05541064,
        -0.11009768, -0.08224115, -0.10641306, -0.18523859, -0.06328088,
        -0.15111968, -0.07306338, -0.13677085, -0.06961808, 10.83867644,
        -0.09424424, -0.07375764, -0.12439555, -0.05656177, -0.05292836,
        -0.0555016 , -0.0555016 , -0.09183516, -0.06025453, -0.06109454,
        -0.07605341, -0.05715419, -0.07498446, -0.09931893, -0.06958796,
        -0.13331125, -0.09750459, -0.07716215, -0.07920566, -0.09028444,
        -0.05319505, -0.09074019, -0.09871204,  4.79219858, -0.07290529,
        -0.08255564, -0.08448653, -0.0875458 , -0.10522908, -0.05573832,
        11.42269696, -0.08808212, -0.10326499, -0.08700628, -0.2654898 ,
        -0.06480078, -0.1499125 , -0.08476106, -0.05633382, -0.07609079,
        -0.18702876, -0.08914536, -0.07512252, -0.09386448, -0.0568427 ,
        -0.08828453, -0.16077609, -0.1115197 , -0.06999544, -0.07095087,
        -0.17528621, -0.07484888, -0.05357606, -0.08029024, -0.06567168,
        -0.06228104, -0.05656177, -0.05541064, -0.09726525, -0.08822397,
        -0.06401546, -0.10786818, -0.06844871, -0.08828453, -0.08393057,
        -0.07155204, -0.05947425, -0.1371931 , -0.06546028, -0.06865684,
        12.83987892, -0.0555016 , -0.05465701, -0.05876133, -0.06619387,
        -0.14771744, -0.10073423, -0.12006981, -0.08774538, -0.05379947,
        -0.08539477, -0.10680717, -0.05633382, -0.06102498, -0.05266857,
        -0.06328088, -0.07861229, -0.05896602, -0.07497618, -0.17749791,
        -0.10396532, -0.08029513, -0.05370029, -0.09691644, -0.08153744,
        -0.06025453, -0.05868375, -0.05715419, -0.05633382, -0.05370029,
         4.0625703 , -0.21259769, -0.08369837, -0.07666787, -0.05624654,
        -0.07970349, -0.06757059, -0.0716525 , -0.10980719, -0.06546028,
        -0.0881067 , -0.12131608, 12.28203009, -0.08316363, -0.14997086,
        -0.06032661, -0.05541064, -0.06495955, -0.05707036, -0.10291951,
        -0.1116718 , -0.059549  , -0.05204303, -0.07230279, -0.06334373,
        -0.06687442, -0.06025453, -0.08029024, -0.09875841, -0.05689227,
        -0.05868375, -0.05737391, -0.1929644 , -0.14516076, -0.05465701,
        -0.05370029, -0.06260278, -0.15439619, -0.07756472, -0.08967241,
        -0.0615528 , -0.0909045 , -0.07028757, -0.08267954, -0.0588671 ,
        -0.0779973 , -0.05370029, -0.08752817, -0.06480078, -0.05689227,
        -0.09012534, -0.17613692, -0.11781628, -0.06178596, -0.07294743,
        -0.05649999, -0.05370029, -0.10815454, -0.09159161, -0.05707036,
        -0.10998123, -0.08096057, -0.14322069, -0.07605341, -0.07605341,
        -0.08241171, -0.13497293, -0.05541064, -0.09591142, -0.11521409,
        -0.06551743, -0.06401546, -0.09521538, -0.05737391, -0.0640763 ,
        -0.05868375, -0.12053227, -0.07791751, -0.06637643, -0.12105456,
        -0.08536789, -0.07934923, -0.10609733, -0.14172422, -0.07495708,
        -0.07251223, -0.07033432, -0.07099639, -0.07247543, -0.21617695,
        -0.11288132, -0.07967075, -0.11002455, -0.0767044 , -0.06966611,
        -0.0508174 , -0.05633382, -0.07028757, -0.13405082, -0.1158868 ,
        -0.05456208, -0.07225957, -0.06229763, -0.24172625, -0.17561912,
        -0.07225957, -0.19495468, -0.07422034, -0.05143312, -0.10538663,
        -0.05456208, -0.05095834, 19.971209  , -0.05573832, -0.05357606,
        -0.08153744, -0.07418022, -0.06825978, -0.05456208, -0.11554103,
        -0.09628913, -0.06825978, -0.05868375, -0.08700628, -0.08976182,
        -0.06102498, -0.12692967, -0.06185315, -0.12667798, -0.08700628,
        -0.18756502, -0.08914536, -0.1336924 , -0.05817519, -0.09294968,
        -0.12912876, -0.07090301, -0.05232114, -0.10202973, -0.06894221,
        -0.0528246 , -0.0662265 , -0.09480683, -0.06127147, -0.46419767,
        -0.15653694, -0.09799353, -0.321133  , -0.11619305, -0.06894221,
        -0.12991902, -0.0528246 , -0.11227814, -0.07024837, -0.05715419,
        -0.14285123, -0.05876133, -0.05405549, -0.08211041]])

In [271]:
from sklearn.cluster import KMeans
km_cv = KMeans(n_clusters=10, random_state=42)
km_cv.fit(X_cv_sc)

KMeans(n_clusters=10, random_state=42)

In [247]:
for n in range(3, 16):
    kmeans = KMeans(n_clusters=n, random_state=42)
    kmeans.fit(X_cv_sc)
    print(n, kmeans.score(X_cv_sc), silhouette_score(X_cv_sc, kmeans.labels_))

3 -6192849.941308153 0.030618977511846012
4 -6167200.862772848 0.07006684173899169
5 -6158029.168175263 0.029904804423303805
6 -6157793.041344845 0.08773619476617435
7 -6109542.040010904 0.052639458771891724
8 -6109569.209759847 -0.00651980502111646
9 -6110420.239448032 0.05351011236338742
10 -6079775.208431132 0.07244279896198835
11 -6083480.954220364 0.0274753871030357
12 -6063034.714193459 0.013632932043164887
13 -6078644.059020367 0.02482936615546004
14 -6043940.519699644 0.019353998932595474
15 -6018761.338540577 -0.005234423062950015

In [127]:
for n in range(3, 16):
    kmeans = KMeans(n_clusters=n, random_state=42)
    kmeans.fit(X_cv_sc)
    print(n, kmeans.score(X_cv_sc), silhouette_score(X_cv_sc, kmeans.labels_))

3 -28940694.445593517 0.1411355764121874
4 -28955605.107846163 0.2078817857404128
5 -28906006.973357055 0.1970638810574114
6 -28884172.496514603 0.028873499206607006
7 -28826976.60191446 0.09113724414951647
8 -28750926.767359056 -0.00945907965969369
9 -28770313.455217905 0.13272966594500843
10 -28623047.328139532 -0.1698422052147124
11 -28627091.92663387 -0.17417764712698425
12 -28529959.223249592 -0.06320072875537311
13 -28532456.60545764 0.003828884180525165
14 -28536859.472120997 -0.04087767521683216
15 -28528615.429199748 -0.19447256285233147

In [128]:
for n in range(16, 30):
    kmeans = KMeans(n_clusters=n, random_state=42)
    kmeans.fit(X_cv_sc)
    print(n, kmeans.score(X_cv_sc), silhouette_score(X_cv_sc, kmeans.labels_))

16 -28425829.79330667 -0.14149180300095468
17 -28359876.988320835 -0.17008951449869308
18 -28357524.207793504 -0.04319445595486965
19 -28348956.86852532 -0.16488235090251382
20 -28274634.919274133 -0.1680674131964157
21 -28300120.653501965 -0.18179577607056205
22 -28135184.75237838 -0.03364704598291362
23 -28082168.265770976 -0.17619106194378809
24 -28051377.07201064 -0.17596067383198333
25 -28086759.84170141 -0.17966950618094796
26 -28147142.57187076 -0.1854144019157126
27 -28087308.061399817 -0.1624141991487051
28 -28006948.424123127 -0.1834039491486426
29 -27967580.520754755 -0.18355555431752105

In [272]:
km_cv.cluster_centers_

array([[-0.05370029, -0.06334373,  0.07628283, ..., -0.05876133,
        -0.05405549, -0.08211041],
       [-0.00800149,  0.00164215,  0.00276817, ...,  0.0058294 ,
         0.0036649 ,  0.00695816],
       [-0.05370029, -0.06334373, -0.07801458, ..., -0.05876133,
        -0.05405549, -0.08211041],
       ...,
       [-0.05370029, -0.06334373, -0.07801458, ..., -0.05876133,
        -0.05405549,  0.02777444],
       [-0.05370029,  0.32577805, -0.07801458, ..., -0.05876133,
        -0.05405549, -0.08211041],
       [ 0.37074458,  0.05162407, -0.07801458, ..., -0.05876133,
        -0.05405549, -0.08211041]])

In [273]:
df['km']=km_cv.labels_

In [274]:
df['km'].value_counts()

1    9808
0     316
9     264
7     106
5      91
2      53
3      42
8      39
4      32
6      30
Name: km, dtype: int64

In [275]:
silhouette_score(X_cv_sc, km_cv.labels_)

0.07244279896198835

In [276]:
df[df['km'] == 6]

,tweet_id,tweet_posted_on,tweets,cleaned_tweets,user_location,user_location_cleaned,polarity,ability,able,access,...,world,worth,would,writer,writing,year,youtube,zero,zoom,km
1693,1415348994444775425,2021-07-14 16:34:30+00:00,The latest The Remote Worker Weekly! https://t...,latest remote worker weekly thanks,United States,US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
2383,1414973814275035137,2021-07-13 15:43:40+00:00,Want to find the job of your dreams? Remote wo...,want find your dream remote work best weekly n...,Anywhere,None,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
3137,1416066623388241925,2021-07-16 16:06:06+00:00,We‚Äôre taking a look at the booming tech job ma...,taking look booming tech market city offering ...,"Indiana, USA",US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
3567,1415764211758678018,2021-07-15 20:04:26+00:00,Free Weekly Marketing Training. Lead generatio...,free weekly marketing training lead generation...,"Chapala, Jalisco Mexico",MX,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
3890,1415586408320884736,2021-07-15 08:17:54+00:00,Financial Freedom Working From Home $$$500$$$T...,financial freedom working from home weekly,"Mississippi, USA",US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
4136,1415370627121356800,2021-07-14 18:00:28+00:00,"24 new fully #remoteimpactjobs (global, region...",fully global regional multiple location weekly...,Florida/ USA,US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
4353,1415253029276856320,2021-07-14 10:13:10+00:00,I need some people to work from üè° \nAll from y...,need some people work from from your cell phon...,"PO Box 2258 Stuart, FL 34995",US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
4420,1415210130308837381,2021-07-14 07:22:43+00:00,Part Time Sales - Paid Weekly Work from Home\...,part time sale paid weekly work from home from...,Canada CA,CA,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
4767,1414934970951421970,2021-07-13 13:09:19+00:00,One-day return to office ‚Äòcould lead to ¬£21m o...,return office could lead weekly saving energy ...,London,GB,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5066,1414649563223404544,2021-07-12 18:15:13+00:00,You want to send your teams home to keep them ...,want send your team home keep them safe great ...,"Richmond, BC Canada",US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5114,1414618585620652039,2021-07-12 16:12:07+00:00,FREE #HomeBasedBusiness Opportunity ‚úÖ ZERO Sta...,free opportunity zero start cost paid weekly j...,"Mesa, AZ",US,0,0,0,0,...,0,0,0,0,0,0,0,1,0,6
5158,1414600830125232131,2021-07-12 15:01:34+00:00,Weekly XAUUSD (GOLD) ST VIP Report\n\nüî∞ Total ...,weekly xauusd gold report total profit pip acc...,t.me/forexsignalsstreet,None,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5234,1414570238159560707,2021-07-12 13:00:00+00:00,'Work from Home' &amp; Ergonomic Product Avail...,work from home ergonomic product availability ...,Plymouth,US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5257,1414554893852061698,2021-07-12 11:59:02+00:00,Do you prefer to work at home or in-office? 63...,prefer work home office worker prefer weekly s...,Maine,US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5627,1417132944414674947,2021-07-19 14:43:17+00:00,"If you are wanting financial and time freedom,...",wanting financial time freedom your give incom...,"Port Elizabeth, South Africa",US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5642,1417126459869704195,2021-07-19 14:17:31+00:00,I‚Äôm not sure what the artwork-of-the-day calen...,sure what artwork calendar telling weekly plan...,"Vermont (think, almost Canada)",US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5839,1417027335895896065,2021-07-19 07:43:38+00:00,Weekly XAUUSD (GOLD) ST VIP Report\n\nüî∞ Total ...,weekly xauusd gold report total profit pip tel...,t.me/forexsignalsstreet,None,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5934,1416939883541663744,2021-07-19 01:56:08+00:00,"Weekly reminder for #WorkFromHome peeps, it's ...",weekly reminder peep monday,Malaysia,MY,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5939,1416933266347630593,2021-07-19 01:29:50+00:00,"With the WFH setup, what changed with your wee...",with setup what changed with your weekly habit,"National Capital Region, Republic of the Phili...",US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
5990,1416867889500626949,2021-07-18 21:10:03+00:00,Spade is looking for Benefits Specialists. Off...,spade looking benefit specialist offer flexibl...,"La Porte, Texas",US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
6276,1416493625492529153,2021-07-17 20:22:52+00:00,"I'll teach first 20 persons on how to earn $7,...",teach first person earn weekly just more detail,United States,US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
6280,1416490993512239109,2021-07-17 20:12:24+00:00,DMüíå Be your own boss make life easier by inves...,your bos make life easier investing earn weekl...,United States,US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
7004,1416918985862488069,2021-07-19 00:33:05+00:00,Bar proposes ethics opinion on remote work ‚Äì V...,proposes ethic opinion remote work virginia la...,"Chicago, IL",US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
7638,1414548000605618176,2021-07-12 11:31:39+00:00,I‚Äôm looking for people interested in working f...,looking people interested working from home on...,"Ohio, USA",US,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
7826,1414255697857024012,2021-07-11 16:10:08+00:00,Looking to find a remote job? There were thou...,looking find remote there were thousand advert...,Surrey UK,GB,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
9760,1417704367571054595,2021-07-21 04:33:55+00:00,"I'm not that greedy, I just want a job that pa...",that greedy just want that pay million year wi...,"Atlanta, GA",US,0,0,0,0,...,0,0,0,0,0,1,0,0,0,6
10137,1417402540639985672,2021-07-20 08:34:34+00:00,I can't make you a millionaire but I can teach...,make millionaire teach make weekly infodm emai...,United States,US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
10157,1417385553784303616,2021-07-20 07:27:04+00:00,My weekly work schedule: \n\nMonday\nWTF is ha...,weekly work schedule monday happening sunday,"New Delhi, India",IN,1,0,0,0,...,0,0,0,0,0,0,0,0,0,6
10348,1417182520353837056,2021-07-19 18:00:17+00:00,We start with the weekly sentence. \nWe invit...,start with weekly sentence invite follow conta...,"Miami, FL",US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
10748,1419004731951886338,2021-07-24 18:41:06+00:00,"Why Weekly Check-in Meetings Are Unproductive,...",weekly check meeting unproductive what about,"Chicago, IL",US,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6

In [277]:
word_frequencies_by_cluster = df.groupby('km').sum()

In [278]:
word_frequencies_by_cluster.head()

,tweet_id,polarity,ability,able,access,according,account,achieve,across,actually,...,workspace,world,worth,would,writer,writing,year,youtube,zero,zoom
km,,,,,,,,,,,,,,,,,,,,,
0,4.475800e+20,71.0,0.0,0.0,4.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,1.0,3.0,2.0,4.0,0.0,0.0,0.0
1,1.389204e+22,4958.0,24.0,42.0,65.0,32.0,90.0,42.0,56.0,32.0,...,49.0,179.0,29.0,135.0,57.0,31.0,211.0,39.0,34.0,75.0
2,7.501999e+19,49.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5.949136e+19,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4.531935e+19,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0

In [279]:
#https://stackoverflow.com/questions/27889873/clustering-text-documents-using-scikit-learn-kmeans-in-python
print("Top terms per cluster:")
order_centroids = km_cv.cluster_centers_.argsort()[:, ::-1]
terms = cv.get_feature_names()
for i in range(14):
    print ("Cluster %d:" % i)
    for ind in order_centroids[i, :20]:
        print( ' %s' % terms[ind])

Top terms per cluster:
Cluster 0:
 compensation
 competitive
 engineer
 role
 check
 equity
 software
 remote
 offering
 javascript
 react
 stack
 senior
 developer
 blockchain
 looking
 engineering
 python
 full
 frontend
Cluster 1:
 home
 employee
 work
 productivity
 tip
 need
 money
 online
 featured
 video
 read
 make
 pandemic
 affiliate
 click
 worker
 tell
 getting
 business
 long
Cluster 2:
 talented
 exciting
 join
 opportunity
 team
 hiring
 apply
 remote
 product
 manager
 designer
 senior
 front
 twitter
 america
 director
 coordinator
 customer
 account
 representative
Cluster 3:
 download
 free
 computer
 link
 code
 play
 using
 training
 software
 report
 microsoft
 traffic
 million
 network
 safe
 impact
 google
 earn
 still
 staff
Cluster 4:
 leadership
 culture
 strategy
 leader
 talk
 trust
 highlight
 style
 coordinator
 transition
 advice
 collaboration
 development
 associate
 head
 focus
 tech
 shift
 team
 news
Cluster 5:
 vacancy
 update
 consultant
 daily
 job
 finance
 manager
 sale
 officer
 analyst
 recruitment
 hour
 live
 friday
 support
 following
 operation
 customer
 assistant
 group
Cluster 6:
 weekly
 bonus
 interested
 profit
 prefer
 info
 freedom
 schedule
 update
 training
 monday
 earn
 financial
 marketing
 report
 sure
 find
 paid
 happy
 easier
Cluster 7:
 type
 name
 incluzion
 salary
 full
 time
 anywhere
 company
 hiring
 order
 number
 brand
 hire
 hour
 detail
 remote
 contract
 state
 part
 power
Cluster 8:
 else
 anyone
 cash
 website
 doe
 want
 miss
 daily
 everyone
 join
 week
 whether
 comment
 something
 game
 morning
 workplace
 every
 thing
 design
Cluster 9:
 going
 place
 back
 forward
 office
 perfect
 country
 think
 ability
 thinking
 work
 different
 better
 great
 many
 amazing
 situation
 come
 follow
 keep
Cluster 10:

IndexError: index 10 is out of bounds for axis 0 with size 10

### TFIDF

In [257]:
#https://stackoverflow.com/questions/37593293/how-to-get-tfidf-with-pandas-dataframe
tfidf = TfidfVectorizer(max_features=5000, min_df=30, max_df=0.5,stop_words=stopwords.words('english'))

In [258]:
X_tfidf = tfidf.fit_transform(X.values.astype('U'))

In [259]:
len(tfidf.get_feature_names())

579

In [260]:
X_tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns = tfidf.get_feature_names())

In [261]:
df1 = pd.concat([originaltweets, X_tfidf_df], axis=1)

In [262]:
df1 = df1.reset_index(drop=True)

In [263]:
df1.head()

,tweet_id,tweet_posted_on,tweets,cleaned_tweets,user_location,user_location_cleaned,polarity,ability,able,access,...,workspace,world,worth,would,writer,writing,year,youtube,zero,zoom
0,1416181616846811137,2021-07-16 23:43:03+00:00,üè° #RemoteWork is on the rise &amp; slowly beco...,rise slowly becoming normal which mean need re...,"New York, NY",US,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1416181380279635970,2021-07-16 23:42:07+00:00,Opportunity to join a fantastic team at a hi-t...,opportunity join fantastic team tech fast pace...,London | New York,US,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1416181225979473920,2021-07-16 23:41:30+00:00,Good news for #JobSeekers open to #RemoteWork!...,good news open this excellent report from remo...,Sydney | Hong Kong | Singapore,HK,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1416180635903868934,2021-07-16 23:39:09+00:00,Four Ways to Energize a Post-Pandemic Workforc...,four way energize post pandemic workforce,"Chicago, IL",US,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1416180231350759425,2021-07-16 23:37:33+00:00,üöë These are the tools that will save your #Rem...,these tool that will save your google meet too...,"Duluth, GA",US,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [264]:
tfidf_col = df1.columns[7:]
tfidf_col_names = df1[tfidf_col]

In [265]:
X_tfidf=tfidf_col_names
sc = StandardScaler()
X_tfidf_sc = sc.fit_transform(X_tfidf)
X_tfidf_sc[0:1]

array([[-0.05202947, -0.0605925 , -0.07706628, -0.05281009, -0.09073248,
        -0.05981162, -0.07195525, -0.05442906, -0.05165782, -0.06070334,
        -0.0902881 , -0.06254891, -0.06329241, -0.05458429, -0.05740021,
         6.18934831, -0.08148408, -0.06703513, -0.05335992, -0.06883784,
        -0.07300717, -0.0562829 , -0.0661336 , -0.12588817, -0.05408662,
        -0.07197645, -0.24756608, -0.06181959, -0.06079042, -0.07265217,
        -0.10182798, -0.09371571, -0.06963362, -0.08638938, -0.05766527,
        -0.07055041, -0.14777603, -0.07141397, -0.07288222, -0.10033531,
        -0.05164207, -0.09717317, 12.42298022, -0.05947399,  4.87447716,
         2.90784022, -0.10757786, -0.05986146, -0.09407135, -0.05679191,
        -0.07766292, -0.05752237, -0.06274608, -0.08108682, -0.06874397,
        -0.06121129, -0.09567407, -0.08170248, -0.22215826, -0.11270131,
        -0.05765915, -0.06963006, -0.08190516, -0.05982127, -0.05604869,
        -0.06183955,  5.08275651, -0.05680164, -0.10782826, -0.06932798,
        -0.06229594, -0.05663528, -0.21190368, -0.05139428, -0.06937725,
        -0.10296145, -0.08963835, -0.08731447, -0.05013506, -0.0505315 ,
        -0.0653433 , -0.05036407,  4.66644431, -0.05686148, -0.07151455,
        -0.05905242, -0.09075705, -0.08026381, -0.20134086, -0.1171863 ,
        -0.11871853, -0.07057613, -0.05628836, -0.05878486, -0.07761582,
        -0.07296591, -0.05304443, -0.0899819 , -0.07480276, -0.08901325,
        -0.060537  , -0.05576415, -0.05340786, -0.06264084, -0.11442334,
        -0.05735178, -0.0670248 , -0.1019728 , -0.08854814, -0.05769751,
        -0.05247414, -0.08561367, -0.14166912, -0.05572466, -0.11057038,
        -0.11614767, -0.11116414, -0.07025867, -0.05669806, -0.05433842,
        -0.08666502, -0.09478191, -0.09153652, -0.07601059, -0.16682375,
        -0.09715214, -0.0666736 , -0.11958049, -0.07946289, -0.05925538,
        -0.06154159, -0.05848591, -0.09704207, -0.09166797, -0.05905972,
        -0.06830707, -0.10218288, -0.05243977, -0.05191717, -0.08354566,
        -0.06677937, -0.05781601, -0.05761455, -0.08516668,  2.05324428,
        -0.10530088, -0.05595855, -0.23037674, -0.08999763, -0.06027436,
        -0.06130664, -0.06400736, -0.06213605, -0.10007601, -0.05218973,
        -0.06565911, -0.058007  , -0.06230091, -0.0544406 , -0.10555167,
        -0.05964262, -0.08323325, -0.0932654 , -0.08242309, -0.06151941,
        -0.08099471, -0.08341956, -0.05426048, -0.12309371, -0.08518916,
        -0.07322693, -0.06630043, -0.05717029, -0.07645085, -0.0715335 ,
        -0.0546685 , -0.06763055, -0.08817292, -0.09609479, -0.06048391,
        -0.05623798, -0.05400857, -0.07409965, -0.14605582, -0.05315312,
        -0.06260856, -0.10903864, -0.0794943 , -0.07502159, -0.11555482,
        -0.06952695, -0.08840779, -0.0537381 , -0.05748614, -0.05387375,
        -0.06260854, -0.06541721, -0.0548206 , -0.051279  , -0.16450594,
        -0.05359167, -0.05679602, -0.06820031, -0.10872956, -0.06748776,
        -0.05710078, -0.1832945 , -0.06312818, -0.11264909, -0.06271718,
        -0.08404195, -0.09218724, -0.05116186, -0.08486906, -0.05686829,
        -0.11946509, -0.12085732, -0.069849  , -0.05434567, -0.13340863,
        -0.07704504, -0.05444025,  6.93792179, -0.06746216, -0.0805506 ,
        -0.05339819, -0.09014208, -0.07157166, -0.07322766, -0.09152333,
        -0.05389239, -0.05652928, -0.19086626, -0.05820151, -0.08014652,
        -0.05719455, -0.08421509, -0.21996575, -0.34111247, -0.05109281,
        -0.11632039, -0.05340899, -0.05825827, -0.15122309, -0.07273154,
        -0.06968674, -0.09222771, -0.07624848, -0.05612029, -0.08012048,
        -0.08737577, -0.08121216, -0.05779891, -0.05204198, -0.07421088,
        -0.08350191, -0.06313078, -0.05683015, -0.06205392, -0.05022968,
        -0.06658234, -0.0547049 , -0.07781839, -0.05479353, -0.07250258,
        -0.06137831, -0.06315235, -0.05967176, -0.06445359, -0.14698283,
        -0.18270628, -0.0763424 , -0.1184145 , -0.05097263, -0.14179272,
        -0.06137967, -0.08510283, -0.08697785, -0.07689572, -0.11649727,
        -0.09228936, -0.05207159, -0.16799277, -0.072713  , -0.05654964,
        -0.05787987, -0.05163235, -0.06880044, -0.16133907, -0.15528365,
        -0.05094125, -0.0667408 , -0.11216676, -0.07955087, -0.0768937 ,
        -0.09915093, -0.06031968, -0.09873493, -0.05454283, -0.09155837,
        -0.05228088, -0.12251033, -0.18130949, -0.09552356, -0.05277004,
        -0.08870625, -0.05736031, -0.05151663, -0.20988847, -0.05423737,
        -0.10706674, -0.07985847, -0.10337162, -0.18029118, -0.05922175,
        -0.14570462, -0.07072019, -0.13537515, -0.06729907,  6.71908483,
        -0.09601733, -0.07364522, -0.12612212, -0.05569899, -0.05146996,
        -0.05309928, -0.0538903 , -0.08764717, -0.05924549, -0.05809306,
        -0.07444086, -0.0548996 , -0.07544535, -0.09703759, -0.06796418,
        -0.13272587, -0.09623471, -0.07654062, -0.07800476, -0.0866114 ,
        -0.0519149 , -0.08847559, -0.09554127,  2.65153177, -0.06814326,
        -0.08193653, -0.08259243, -0.08419082, -0.10375267, -0.05594963,
         6.31101626, -0.08435092, -0.09971803, -0.08569831, -0.25194757,
        -0.0640139 , -0.15604165, -0.08194573, -0.05488574, -0.07325418,
        -0.17924091, -0.08495438, -0.0734    , -0.09040933, -0.06149511,
        -0.08728183, -0.15271339, -0.10800959, -0.06798228, -0.06857343,
        -0.16659638, -0.07135134, -0.0540202 , -0.07747246, -0.06330611,
        -0.06241302, -0.05564088, -0.0542942 , -0.093485  , -0.08624259,
        -0.06159736, -0.10333148, -0.06582346, -0.08662877, -0.08230623,
        -0.07144226, -0.05697345, -0.13280941, -0.06325828, -0.06674817,
         7.1484551 , -0.05372829, -0.05359914, -0.05548666, -0.06725185,
        -0.14052319, -0.09627518, -0.11413904, -0.08541684, -0.05302006,
        -0.08155053, -0.10557625, -0.05581215, -0.05778298, -0.05407813,
        -0.0592145 , -0.07634463, -0.05807743, -0.07403801, -0.16670011,
        -0.10155555, -0.07995017, -0.05093984, -0.09384251, -0.07852074,
        -0.05961555, -0.05732584, -0.05560081, -0.05571455, -0.05220942,
         1.81659944, -0.20512685, -0.08141388, -0.07382432, -0.05460132,
        -0.0757158 , -0.06567131, -0.06900841, -0.10577278, -0.06325442,
        -0.08603646, -0.11635867,  8.3442412 , -0.07989981, -0.14229577,
        -0.05909418, -0.05315432, -0.06345849, -0.05325158, -0.09943547,
        -0.11399122, -0.0578544 , -0.05051447, -0.06898554, -0.0618545 ,
        -0.0645299 , -0.05814209, -0.07802523, -0.09684313, -0.05551442,
        -0.05654206, -0.05677   , -0.18567292, -0.14078397, -0.05388715,
        -0.05158144, -0.06018532, -0.14964823, -0.07519094, -0.0862017 ,
        -0.06059699, -0.08477905, -0.06644023, -0.07787413, -0.05815262,
        -0.07689273, -0.05082557, -0.08849791, -0.06325383, -0.05709903,
        -0.09254915, -0.17218263, -0.11408968, -0.05887393, -0.0703437 ,
        -0.05548322, -0.05062644, -0.10354602, -0.0884947 , -0.05668519,
        -0.11028674, -0.07924532, -0.13603701, -0.07305085, -0.07432773,
        -0.08027063, -0.12995783, -0.05406244, -0.09587346, -0.10965845,
        -0.06381566, -0.06170286, -0.09268062, -0.05664611, -0.06190385,
        -0.05544772, -0.11500697, -0.07544091, -0.06506988, -0.11618698,
        -0.08231429, -0.07749515, -0.10314616, -0.13643979, -0.07140181,
        -0.0722514 , -0.07048962, -0.06704569, -0.07073848, -0.21296579,
        -0.10886753, -0.07617648, -0.10613644, -0.07382745, -0.06889992,
        -0.0534809 , -0.05514712, -0.06766173, -0.12806454, -0.10908244,
        -0.0529228 , -0.06951349, -0.06195319, -0.22874753, -0.16626722,
        -0.0656426 , -0.18111929, -0.07254909, -0.05104332, -0.10587038,
        -0.05329207, -0.05037456, 12.22043492, -0.05561071, -0.05258265,
        -0.0795171 , -0.0712711 , -0.06485278, -0.05290904, -0.11128556,
        -0.09417047, -0.0659168 , -0.05655173, -0.08563245, -0.08852527,
        -0.05830132, -0.12591982, -0.05929433, -0.12367771, -0.08192139,
        -0.17744232, -0.08613133, -0.12826703, -0.05711945, -0.09001348,
        -0.12325638, -0.06982268, -0.05128946, -0.09905204, -0.06643395,
        -0.05060368, -0.06510172, -0.09095535, -0.06180476, -0.440154  ,
        -0.15228812, -0.09535928, -0.30346586, -0.11164254, -0.06388421,
        -0.1252729 , -0.05157416, -0.10806565, -0.06899363, -0.05392039,
        -0.13645423, -0.05745482, -0.05435346, -0.08037778]])

In [266]:
from sklearn.cluster import KMeans
km_tfidf = KMeans(n_clusters=15, random_state=42)
km_tfidf.fit(X_tfidf_sc)

KMeans(n_clusters=15, random_state=42)

In [267]:
for i in range(3, 16):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_tfidf_sc)
    print(i, kmeans.score(X_tfidf_sc), silhouette_score(X_tfidf_sc, kmeans.labels_))

3 -6187597.521275744 -0.038879401915755354
4 -6180641.6222398775 -0.03457205172495074
5 -6139690.319021157 -0.0397058461157566
6 -6141834.717026974 -0.035018996402061485
7 -6122730.717792992 -0.05529930688223335
8 -6122383.641500191 -0.03425790558883513
9 -6101773.09894736 -0.03542206855726427
10 -6093166.549280853 -0.035714196670819834
11 -6084557.449298803 -0.037167380276226736
12 -6071406.36081785 -0.047053334239604484
13 -6056554.298489784 -0.036605538764313605
14 -6052835.335485422 -0.03981460894525785
15 -6037993.876886576 0.0010330051345629424

In [69]:
km_tfidf.cluster_centers_

array([[-0.06954607, -0.04856609, -0.02368941, ..., -0.04741743,
        -0.04745091,  0.17179848],
       [ 0.00276813,  0.00045208,  0.00094291, ...,  0.00188735,
         0.00188868,  0.00225768],
       [-0.06954607, -0.04856609, -0.02368941, ..., -0.04741743,
        -0.04745091, -0.06685293],
       ...,
       [-0.06954607, -0.04856609, -0.02368941, ..., -0.04741743,
        -0.04745091, -0.06685293],
       [-0.06954607, -0.04856609, -0.02368941, ..., -0.04741743,
        -0.04745091, -0.06685293],
       [-0.06954607, -0.04856609, -0.02368941, ..., -0.04741743,
        -0.04745091, -0.06685293]])

In [70]:
df1['km']=km_tfidf.labels_

In [71]:
df1['km'].value_counts()

1     21305
10      322
14      154
5        99
7        37
0        36
12       34
2        30
4        27
9        22
13       21
8        21
3        17
6        16
11       12
Name: km, dtype: int64

In [72]:
silhouette_score(X_tfidf_sc, km_tfidf.labels_)

-0.1343755446812336

In [73]:
word_frequency_by_cluster = df1.groupby('km').sum()

In [74]:
word_frequency_by_cluster.head()

,tweet_id,polarity,ability,able,absolutely,accelerated,access,accessible,accessory,accommodation,...,year,yesterday,york,young,youtube,ysense,zero,zombie,zone,zoom
km,,,,,,,,,,,,,,,,,,,,,
0,5.096904e+19,26.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.363649,0.000000,...,0.515870,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.228903
1,3.017780e+22,11007.0,46.009167,20.921029,5.445305,52.927129,36.233883,7.675012,8.888907,6.530289,...,90.572023,8.007466,9.079564,14.752173,28.175194,10.308512,20.559031,18.383023,22.289003,39.229311
2,4.256708e+19,18.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.402177,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2.407026e+19,17.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.270438,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,3.823612e+19,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [75]:
print("Top terms per cluster:")
order_centroids = km_tfidf.cluster_centers_.argsort()[:, ::-1]
terms = tfidf.get_feature_names()
for i in range(14):
    print ("Cluster %d:" % i)
    for ind in order_centroids[i, :20]:
        print( ' %s' % terms[ind])

Top terms per cluster:
Cluster 0:
 efficient
 remain
 enabling
 profitable
 productive
 potential
 enter
 edition
 reach
 hard
 virtual
 requires
 setup
 consistent
 stop
 tool
 resource
 discover
 desktop
 control
Cluster 1:
 work
 remote
 apply
 hiring
 team
 employee
 business
 pandemic
 looking
 opportunity
 find
 tip
 developer
 life
 post
 design
 many
 job
 service
 full
Cluster 2:
 considerably
 dreaming
 longing
 expected
 tied
 scenery
 number
 rise
 five
 extra
 next
 might
 space
 year
 since
 people
 working
 remotely
 change
 home
Cluster 3:
 insightful
 decrease
 increase
 article
 director
 security
 check
 conducted
 habit
 reliable
 internal
 explained
 machine
 safe
 webinar
 detail
 changed
 across
 learning
 trend
Cluster 4:
 smartbox
 steady
 pocket
 airtel
 workflow
 wifi
 device
 internet
 keep
 home
 working
 shed
 sorry
 summit
 webcam
 mine
 modus
 friendship
 architecture
 acquisition
Cluster 5:
 infracloud
 reliability
 site
 database
 ready
 cloud
 native
 engineer
 backend
 wanna
 senior
 tech
 engineering
 want
 interested
 software
 manager
 product
 mailchimp
 join
Cluster 6:
 wonder
 sell
 wrong
 trying
 feel
 online
 develop
 kept
 sometimes
 playing
 sale
 region
 world
 workload
 people
 way
 supply
 folk
 best
 percent
Cluster 7:
 conservatory
 lamp
 pic
 combination
 telephone
 retro
 colour
 busy
 taking
 making
 everywhere
 else
 sale
 shed
 sorry
 summit
 webcam
 mine
 modus
 friendship
Cluster 8:
 war
 millennials
 thrilled
 beer
 hottest
 higher
 perk
 talent
 tech
 free
 office
 reporting
 early
 late
 center
 longer
 people
 shed
 sorry
 summit
Cluster 9:
 completely
 bootcamp
 prepared
 worldwide
 activity
 funnel
 sabio
 autopilot
 changed
 firm
 found
 implementation
 changer
 restriction
 long
 total
 different
 limited
 stressed
 profit
Cluster 10:
 free
 earn
 second
 nice
 paid
 minute
 video
 related
 daily
 youtube
 autopilot
 activate
 dashboard
 might
 make
 look
 today
 inside
 invite
 traffic
Cluster 11:
 county
 union
 appear
 continuing
 past
 mean
 potentially
 commute
 region
 expand
 accountant
 payroll
 administrator
 response
 inbound
 week
 leadership
 economic
 posting
 back
Cluster 12:
 climbed
 difference
 positive
 high
 world
 success
 make
 shed
 sorry
 summit
 webcam
 mine
 modus
 friendship
 architecture
 acquisition
 bakery
 meme
 exercise
 crowd
Cluster 13:
 bacak
 matt
 legend
 million
 digital
 marketing
 watch
 paid
 video
 know
 make
 shed
 sorry
 summit
 webcam
 mine
 modus
 friendship
 architecture
 acquisition